name: Run tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        ruby: [ '3.1', '3.2', '3.3', '3.4', '3.5' ]
        gemfile: [ sidekiq_6_1, sidekiq_7, sidekiq_8 ]
        redis: [ '7.4-alpine', '8.2-alpine' ]
        exclude:
          - ruby: '3.1'
            gemfile: sidekiq_8
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/${{ matrix.gemfile }}.gemfile
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:${{ matrix.redis }}
        ports:
          - 6379:6379
    steps:
      - uses: actions/checkout@v7
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run tests
        run: bundle exec rake
        env:
          REDIS_URL: redis://localhost:6379/0
